const rhyme = 
[
    ['stump', 'hump'],
    ['sweeter', 'peter'],
    ['attack her', 'wrapper'],
    ['silly', 'willy'],
    ['prick', 'dick'],
    ['doubt', 'spout'],
    ['skin', 'break her in'],
    ['loner', 'boner'],
    ['wrong', 'dong'],
    ['sack it', 'whack it'],
    ['spunkey', 'monkey'],
    ['thighs', 'condomize'],
    ['sick', 'dick'],
    ['heat', 'meat'],
    ['tap it', 'cap it'],
    ['December', 'member'],
    ['wrap it', 'tap it'],
    ['fool', 'tool'],
    ['selection', 'erection'],
    ['foil', 'oil'],
    ['love her', 'cover'],
    ['mistake', 'snake'],
    ['cleaner', 'weiner'],
    ['deck her', 'pecker'],
    ['bag it', 'tag it'],
    ['rocket', 'pecker'],
    ['glove', 'love'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
    ['mistake', 'snake'],
];