const rhyme = 
[
    ['stump', 'hump'],
    ['sweeter', 'peter'],
    ['attack her', 'wrapper'],
    ['silly', 'willy'],
    ['prick', 'dick'],
    ['doubt', 'spout'],
    ['skin', 'break her in'],
    ['loner', 'boner'],
    ['wrong', 'dong'],
    ['sack it', 'whack it'],
    ['spunkey', 'monkey'],
    ['thighs', 'condomize'],
    ['sick', 'dick'],
    ['heat', 'meat'],
    ['tap it', 'cap it'],
    ['December', 'member'],
    ['wrap it', 'tap it'],
    ['fool', 'tool'],
    ['selection', 'erection'],
    ['foil', 'oil'],
    ['love her', 'cover'],
    ['mistake', 'snake'],
    ['cleaner', 'weiner'],
    ['deck her', 'pecker'],
    ['bag it', 'tag it'],
    ['rocket', 'pecker'],
    ['glove', 'love'],
    ['jiffy', 'stiffy'],
    ['joke', 'poke'],
    ['Venus', 'penis'],
    ['armor', 'harm her'],
    ['sigh', 'one eye'],
    ['eager', 'beaver'],
    ['dink', 'sink'],
    ['joker', 'poke her'],
    ['surprise her', 'geyser'],
    ['lumber', 'pump her'],
    ['wrinkle', 'sprinkle'],
    ['bristle', 'whistle'],
    ['snake', 'shake and bake'],
    ['peter', 'neater'],
    ['sling', 'bling'],
];