const freeTheWilly = 
[
    "Cover your stump, before you hump!",
    "It will be sweeter, if you wrap your peter!",
    "No balloon, no party!",
    "Before you attack her, wrap your wrapper!",
    "Don't be silly, protect your will!",
    "Don't be a dick, cover your dick!",
    "When in doubt, shroud your spout!",
    "Cover your skin, before you break her in!",
    "Don't be a loner, cover your boner!",
    "You can't wrong if you shield your dong!",
    "If you're not going to sack it, go home and whack it!",
    "If you think she's spunky, cover your monkey!",
    "If you slip between her thighs, be sure to condomize!",
    "She won't get sick if you wrap your dick!",
    "If you go into heat, package your meat!",
    "Before you tap it, cap it!",
    "Especially in December, gift-wrap your member!",
    "Wrap it before you tap it!",
    "Don't be a fool, vulcanize your tool!",
    "Before you dig for those pearls, cover your jewel!",
    "The right selection, protect your erection!",
    "Wrap it in foil before checking her oil!",
    "If you really love her, wear a cover!", 
    "Don't make a mistake, muzzle your snake", 
    "Sex is cleaner with a packaged wiener!", 
    "Never deck her with an unwrapped pecker!", 
    "Bag it before you tag it!",
    "If you can't shield your rocket, leave it in your pocket!", 
    "No glove, no love!",
    "Don't be in such a jiffy, cover your stiffy!",
    "AIDS is no joke, be sure to wrap before you poke!", 
    "While you're undressing Venus, dress up your penis!",
    "A crank with armor, will never harm her!",
    "If you think she'll sigh, cover old one eye!", 
    "Even if she's eager, protect her beaver!",
    "Put a condom on your dink, before you dart it in her sink!", 
    "Cloak the joker, before you poke her!",
    "Encase that torch, before you paint her porch!",
    "Don't surprise her; plug your Geyser!", 
    "Safe Sex or No Sex!",
    "Cover that lumber, before you pump her!", 
    "Protect her wrinkle, before you sprinkle!",
    "She won't bristle if you wrap your whistle!", 
    "Cage that snake, then shake and bake!", 
    "Cover your peter, it will be much neater!",
    "Put on the sling, before you get some bling!",
];